# Generated by Django 5.2 on 2026-01-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_users_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Admin"), (2, "Member"), (3, "Tester")], default=2
            ),
        ),
    ]
