# Generated by Django 5.2 on 2026-01-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="owner_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
