# Generated by Django 5.2 on 2026-01-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on_hold", "On Hold"),
                    ("test", "Test"),
                    ("archived", "Archived"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
