# Generated by Django 5.2 on 2026-01-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_projects_appointed_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="appointed_person",
        ),
    ]
